name: "Build for Linux"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

  workflow_dispatch:
    inputs:
      upload_installer:
        description: 'Upload installer artifact? [true, false]'
        required: false
        default: 'false'
      upload_library:
        description: 'Upload library artifact? [true, false]'
        required: false
        default: 'false'

jobs:
  build:
    name: 'Linux build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Install cmake'
        run: sudo apt-get update && sudo apt-get install -yq cmake

      - name: 'Configure cmake for project'
        run: cmake -B build
      
      - name: 'Build'
        run: cmake --build ./build
      
      - name: 'Upload installer'
        if: ${{ github.event.inputs.upload_installer == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: 'Searcher'
          path: ${{ github.workspace }}/build/Searcher
      
      - name: 'Upload library'
        if: ${{ github.event.inputs.upload_library == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: 'libsearch'
          path: ${{ github.workspace }}/build/libsearch.a
