name: "Build for Windows"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

  workflow_dispatch:
    inputs:
      upload_installer:
        description: 'Upload installer artifact? [true, false]'
        required: false
        default: 'false'
      upload_library:
        description: 'Upload library artifact? [true, false]'
        required: false
        default: 'false'

jobs:
  build:
    name: 'Windows build'
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      
      - name: 'Configure cmake for project'
        run: cmake -B ./build/windows -G "Visual Studio 16 2019" -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Release
      
      - name: 'Build'
        run: cmake --build ./build/windows --config Release
      
      - name: 'Upload installer'
        if: ${{ github.event.inputs.upload_installer == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: 'Searcher'
          path: ${{ github.workspace }}/build/windows/Release/Searcher.exe
      
      - name: 'Upload library'
        if: ${{ github.event.inputs.upload_library == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: 'libsearch'
          path: ${{ github.workspace }}/build/windows/Release/search.lib
